theme: jekyll-theme-minimal
title: Augur.Guide
description1: A friendly user guide to the prediction market protocol owned and operated by the people that use it.
description2: description2 test test test.
logo: https://augur.guide/assets/images/Augur.Guide-Logo-96x96.png
show_downloads: false
google_analytics: UA-12186523-5
